local t = {}
local getShapeArray = require("utils.get-shape-array");
local widget = require("widget")

local createLevelObjects = function (mainFunc, shapeArrayParameters)
    --------  CREATE OBJECTS HERE   -----------

    --SCREEN 1-1
    table.insert(shapeArrayParameters, getShapeArray("shape","bar1_1_1", {1, 1, 2, 1}, "bar", {"vert", 3}))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan1_1_1", {1, 1, 2, 1}, "right"))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar2_1_1", {1, 1, 4, 1}, "bar", {"vert", 3}))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle1_1_1", {1, 1, 5, 1}, "triangleBottomRightShape"))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"triangle1_1_1"},{"flip-horizontal"}})
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle2_1_1", {1, 1, 1, 2}, "triangleBottomRightShape", {1, 3}))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle3_1_1", {1, 1, 3, 2}, "triangleBottomLeftShape", {1, 4}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"triangle3_1_1"},{"flip-horizontal"}})
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle4_1_1", {1, 1, 6, 2}, "triangleBottomLeftShape"))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar3_1_1", {1, 1, 7, 2}, "bar", {"vert", 3}))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan2_1_1", {1, 1, 7, 2}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("gun","gun1_1_1", {1, 1, 5, 3}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan3_1_1", {1, 1, 1, 4}, "left"))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar4_1_1", {1, 1, 2, 4}, "bar", {"horz", 2}))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan2_1_1", {1, 1, 2, 4}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar5_1_1", {1, 1, 3, 4}, "bar", {"horz", 3}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"bar5_1_1"},{"switchSlide"},{},{2},{1},{1,1,3,3},{2},{1,1,3,4}})
    table.insert(shapeArrayParameters, getShapeArray("backFire","backFire1_1_1", {1, 1, 6, 4}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"backFire1_1_1"},{"slide"},{},{2},{1},{1,1,6,5},{2},{1,1,6,4},{3},{1,1,7,4}})
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan4_1_1", {1, 1, 1, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("door","door1_1_1", {1, 1, 1, 5, "down", "disabled"}))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar6_1_1", {1, 1, 2, 6}, "bar", {"vert", 2}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"bar6_1_1"},{"switchSlide"},{},{2},{1},{1,1,1,6},{2},{1,1,2,6}})
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan5_1_1", {1, 1, 3, 5}, "left"))
    table.insert(shapeArrayParameters, getShapeArray("item","mystery-block", {1, 1, 4, 5}, {
        {name = "triangle", properties = {shape = "triangleTopRightShape"} },
        {name = "autoFan", properties = {directions = {"left"} } },
        {name = "manualFan", properties = {directions = {"left"} } },
        {name = "simple"},
        {name = "backFire"},
        {name = "spitter", properties = {directions = {"down", "left"} } }
    }))
    table.insert(shapeArrayParameters, getShapeArray("door","door2_1_1", {1, 1, 6, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar7_1_1", {1, 1, 7, 6}, "bar", {"vert"}))

    --SCREEN 1-2
    table.insert(shapeArrayParameters, getShapeArray("door","door1_1_2", {1, 2, 1, 1}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle1_1_2", {1, 2, 3, 1}, "triangleTopLeftShape", {1, 5, "breakable"}))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle2_1_2", {1, 2, 5, 1}, "triangleTopLeftShape", {1, _, "breakable"}))
    table.insert(shapeArrayParameters, getShapeArray("door","door2_1_2", {1, 2, 6, 1}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter1_1_2", {1, 2, 3, 2}, {"none","none","down","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter1_1_2"},{"slide"},{},{2},{1},{1,2,2,2},{2},{1,2,3,2}})
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan1_1_2", {1, 2, 6, 3}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter2_1_2", {1, 2, 5, 4}, {"none","none","down","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter2_1_2"},{"slide"},{},{2},{1},{1,2,2,4},{2},{1,2,5,4},{3},{1,2,7,4}})
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle3_1_2", {1, 2, 1, 5}, "triangleTopRightShape", {1, _, "icy"}))
    table.insert(shapeArrayParameters, getShapeArray("door","door3_1_2", {1, 2, 2, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("door","door4_1_2", {1, 2, 3, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("door","door5_1_2", {1, 2, 5, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle4_1_2", {1, 2, 6, 5}, "triangleTopLeftShape", {1, _, "icy"}))
    table.insert(shapeArrayParameters, getShapeArray("door","door6_1_2", {1, 2, 7, 5}, "down"))

    --SCREEN 2-2
    table.insert(shapeArrayParameters, getShapeArray("shape","bar1_2_2", {2, 2, 1, 1}, "bar", {"vert", 3}))
    table.insert(shapeArrayParameters, getShapeArray("backFire","backFire1_2_2", {2, 2, 1, 1}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"backFire1_2_2"},{"slide"},{},{1},{1},{2,2,1,1},{2},{2,2,1,2},{3},{2,2,2,2},{4},{2,2,2,3}})
    table.insert(shapeArrayParameters, getShapeArray("shape","bar2_2_2", {2, 2, 4, 1}, "bar", {"horz", 4}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"bar2_2_2"},{"slide"},{},{2},{1},{2,2,4,1},{2},{2,2,4,2}})
    table.insert(shapeArrayParameters, getShapeArray("shape","bar3_2_2", {2, 2, 5, 1}, "bar", {"vert", 4}))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle1_2_2", {2, 2, 7, 1}, "triangleBottomLeftShape"))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"triangle1_2_2"},{"slide"},{},{3},{1},{2,2,5,2},{2},{2,2,7,2},{3},{2,2,7,1}})
    table.insert(shapeArrayParameters, getShapeArray("shape","bar4_2_2", {2, 2, 1, 2}, "bar", {"horz", 3}))
    table.insert(shapeArrayParameters, getShapeArray("door","door1_2_2", {2, 2, 1, 3}, "left"))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar5_2_2", {2, 2, 4, 3}, "bar", {"vert"}))
    table.insert(shapeArrayParameters, getShapeArray("simple","simple1_2_2", {2, 2, 6, 3}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"simple1_2_2"},{"slide"},{},{3},{1},{2,2,3,4},{2},{2,2,5,4},{3},{2,2,6,3}})
    table.insert(shapeArrayParameters, getShapeArray("shape","bar6_2_2", {2, 2, 8, 3}, "bar", {"horz", 2}))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar7_2_2", {2, 2, 2, 5}, "bar", {"vert", 3}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"bar7_2_2"},{"switchSlide"},{},{1},{1},{2,2,2,5},{2},{2,2,7,5}})
    table.insert(shapeArrayParameters, getShapeArray("backFire","backFire2_2_2", {2, 2, 3, 5}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"backFire2_2_2"},{"slide"},{},{2},{1},{2,2,1,5},{2},{2,2,3,5}})
    table.insert(shapeArrayParameters, getShapeArray("door","door2_2_2", {2, 2, 4, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan1_2_2", {2, 2, 5, 5}, "down"))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"autoFan1_2_2"},{"switchSlide"},{},{2},{1},{2,2,4,5},{2},{2,2,5,5}})
    table.insert(shapeArrayParameters, getShapeArray("shape","bar8_2_2", {2, 2, 3, 6}, "bar", {"vert", 3}))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar9_2_2", {2, 2, 6, 6}, "bar", {"vert", 3}))

    --SCREEN 1-3
    table.insert(shapeArrayParameters, getShapeArray("door","door1_1_3", {1, 3, 2, 1}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("door","door2_1_3", {1, 3, 3, 1}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("simple","simple1_1_3", {1, 3, 3, 1}))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan1_1_3", {1, 3, 6, 2}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan1_1_3", {1, 3, 7, 2}, "left"))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle1_1_3", {1, 3, 3, 3}, "triangleTopRightShape", {1, _, "icy"}))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle2_1_3", {1, 3, 4, 3}, "triangleBottomLeftShape", {1, _, "icy"}))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle3_1_3", {1, 3, 5, 3}, "triangleBottomRightShape"))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"triangle3_1_3"},{"switchSlide"},{},{1},{1},{1,3,5,3},{2},{1,3,6,3}})
    table.insert(shapeArrayParameters, getShapeArray("door","door3_1_3", {1, 3, 7, 3}, "right"))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle4_1_3", {1, 3, 3, 4}, "triangleBottomLeftShape", {1, 2, "breakable"}))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan1_1_3", {1, 3, 5, 4}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar1_1_3", {1, 3, 6, 4}, "bar", {"vert", 3}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"bar1_1_3"},{"switchSlide"},{},{2},{1},{1,3,5,4},{2},{1,3,6,4}})
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan1_1_3", {1, 3, 7, 4}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("door","door4_1_3", {1, 3, 2, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("simple","simple1_1_3", {1, 3, 4, 5}))
    table.insert(shapeArrayParameters, getShapeArray("door","door5_1_3", {1, 3, 4, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("door","door6_1_3", {1, 3, 5, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan1_1_3", {1, 3, 6, 5}, "right"))
    table.insert(shapeArrayParameters, getShapeArray("door","door7_1_3", {1, 3, 7, 5}, "right", {"disabled"}))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar2_1_3", {1, 3, 3, 6}, "bar", {"vert", 2}))

    --SCREEN 2-3
    table.insert(shapeArrayParameters, getShapeArray("shape","bar1_2_3", {2, 3, 1, 1}, "bar", {"vert", 2}))
    table.insert(shapeArrayParameters, getShapeArray("door","door1_2_3", {2, 3, 2, 1}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("door","door2_2_3", {2, 3, 4, 1}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar2_2_3", {2, 3, 3, 2}, "bar", {"vert"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"bar1_1_3"},{"slide"},{},{2},{1},{2,3,2,2},{2},{2,3,3,2}})
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle1_2_3", {2, 3, 7, 2}, "triangleBottomLeftShape", {1, 4}))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar3_2_3", {2, 3, 2, 3}, "bar", {"vert", 2}))
    table.insert(shapeArrayParameters, getShapeArray("item","map", {2, 3, 4, 3}))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan1_2_3", {2, 3, 7, 3}, "right"))
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter1_2_3", {2, 3, 2, 4}, {"none","none","down","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter1_2_3"},{"slide"},{},{2},{1},{2,3,2,3},{2},{2,3,2,4}})
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter2_2_3", {2, 3, 6, 4, "up","none","none","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter2_2_3"},{"slide"},{},{2},{1},{2,3,6,3},{2},{2,3,6,4}})
    --table.insert(shapeArrayParameters, getShapeArray("item","coins", {2, 3, 7, 4}, 250))
    table.insert(shapeArrayParameters, getShapeArray("simple","simple1_2_3", {2, 3, 3, 5}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"simple1_2_3"},{"slide"},{},{2},{1},{2,3,1,5},{2},{2,3,3,5},{3},{2,3,4,5}})
    table.insert(shapeArrayParameters, getShapeArray("shape","bar4_2_3", {2, 3, 5, 5}, "bar", {"vert"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"bar4_2_3"},{"slide"},{},{1},{1},{2,3,5,5},{2},{2,3,6,5}})
    table.insert(shapeArrayParameters, getShapeArray("door","door3_2_3", {2, 3, 6, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan3_2_3", {2, 3, 7, 5}, "up"))

    --SCREEN 1-4
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter1_1_4", {1, 4, 1, 1}, {"none","none","none","left"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter1_1_4"},{"switchSlide"},{},{1},{1},{1,4,1,1},{2},{1,4,3,1}})
    table.insert(shapeArrayParameters, getShapeArray("door","door1_1_4", {1, 4, 2, 1, "up", "enabled"}))
    table.insert(shapeArrayParameters, getShapeArray("door","door2_1_4", {1, 4, 4, 1, "up", "enabled"}))
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter2_1_4", {1, 4, 7, 1, "up","none","none","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter2_1_4"},{"switchSlide"},{},{2},{1},{1,4,6,1},{2},{1,4,7,1}})
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter3_1_4", {1, 4, 1, 2, "up","none","none","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter3_1_4"},{"switchSlide"},{},{1},{1},{1,4,1,2},{2},{1,4,3,2}})
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter4_1_4", {1, 4, 7, 2}, {"none","none","none","left"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter4_1_4"},{"switchSlide"},{l},{2},{1},{1,4,5,2},{2},{1,4,7,2}})
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter5_1_4", {1, 4, 2, 3, "up","right","none","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter5_1_4"},{"slide"},{},{1},{1},{1,4,2,3},{2},{1,4,3,3}})
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter6_1_4", {1, 4, 7, 3}, {"none","none","down","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter6_1_4"},{"switchSlide"},{},{2},{1},{1,4,6,3},{2},{1,4,7,3}})
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter7_1_4", {1, 4, 2, 4}, {"none","none","down","none"}))
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter8_1_4", {1, 4, 5, 4, "up","none","none","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter8_1_4"},{"slide"},{},{2},{1},{1,4,4,4},{2},{1,4,5,4}})
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter9_1_4", {1, 4, 7, 4}, {"none","right","none","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter9_1_4"},{"switchSlide"},{},{2},{1},{1,4,6,4},{2},{1,4,7,4}})
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter10_1_4", {1, 4, 1, 5}, {"none","right","none","none"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter10_1_4"},{"switchSlide"},{},{1},{1},{1,4,1,5},{2},{1,4,2,5}})
    table.insert(shapeArrayParameters, getShapeArray("endPoint","endPoint1_1_4", {1, 4, 3, 5}))
    table.insert(shapeArrayParameters, getShapeArray("spitter","spitter11_1_4", {1, 4, 7, 5}, {"none","none","none","left"}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"spitter11_1_4"},{"switchSlide"},{},{2},{1},{1,4,6,5},{2},{1,4,7,5}})
    table.insert(shapeArrayParameters, getShapeArray("shape","bar1_1_4", {1, 4, 2, 6}, "bar", {"vert", 3}))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar2_1_4", {1, 4, 3, 6}, "bar", {"vert", 3}))

    --SCREEN 2-4
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle1_2_4", {2, 4, 1, 1}, "triangleBottomLeftShape", {1, 2, "icy"}))
    table.insert(shapeArrayParameters, getShapeArray("door","door1_2_4", {2, 4, 2, 1}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan1_2_4", {2, 4, 3, 1}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("door","door2_2_4", {2, 4, 4, 1}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("door","door3_2_4", {2, 4, 6, 1}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan2_2_4", {2, 4, 4, 2}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar1_2_4", {2, 4, 4, 2}, "bar", {"horz", 3}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"bar1_2_4"},{"slide"},{},{2},{1},{2,4,4,1},{2},{2,4,4,2}})
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle2_2_4", {2, 4, 7, 2}, "triangleTopLeftShape", {1, _, "icy"}))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan3_2_4", {2, 4, 1, 3}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle3_2_4", {2, 4, 2, 3}, "triangleBottomLeftShape", {1, _, "icy"}))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle4_2_4", {2, 4, 3, 3}, "triangleTopRightShape", {1, _, "icy"}))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan4_2_4", {2, 4, 4, 3}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle5_2_4", {2, 4, 5, 3}, "triangleBottomRightShape", {1, _, "icy"}))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan1_2_4", {2, 4, 6, 3}, "left"))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan2_2_4", {2, 4, 2, 4}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan3_2_4", {2, 4, 6, 4}, "right"))
    table.insert(shapeArrayParameters, getShapeArray("door","door4_2_4", {2, 4, 1, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan4_2_4", {2, 4, 2, 5}, "down"))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan5_2_4", {2, 4, 4, 5}, "left"))
    table.insert(shapeArrayParameters, getShapeArray("autoFan","autoFan6_2_4", {2, 4, 5, 5}, "right"))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan5_2_4", {2, 4, 7, 5}, "down"))

    --SCREEN 2-5
    table.insert(shapeArrayParameters, getShapeArray("door","door1_2_5", {2, 5, 6, 1}, "up"))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar1_2_5", {2, 5, 1, 2}, "bar", {"horz", 4}))
    --table.insert(shapeArrayParameters, getShapeArray("item","coins", {2, 5, 1, 2}, 500))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar2_2_5", {2, 5, 1, 3}, "bar", {"vert", 4}))
    table.insert(shapeArrayParameters, getShapeArray("shape","bar3_2_5", {2, 5, 1, 3}, "bar", {"horz", 3}))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle1_2_5", {2, 5, 3, 3}, "triangleBottomLeftShape", {1, 4}))
    table.insert(mainFunc.allLevelSettings.transitionArrayIndex,{{"triangle1_2_5"},{"flip-vertical"}})
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle2_2_5", {2, 5, 1, 5}, "triangleTopRightShape", {1, _, "icy"}))
    table.insert(shapeArrayParameters, getShapeArray("manualFan","manualFan1_2_5", {2, 5, 3, 5}, "right"))
    table.insert(shapeArrayParameters, getShapeArray("shape","triangle3_2_5", {2, 5, 6, 5}, "triangleTopLeftShape", {1, _, "icy"}))

    --SWITCHES
    table.insert(shapeArrayParameters, getShapeArray("switch","switch1_1_1", {1, 1, 1, 3}, { {"door-open","door1_1_1"} }))
    table.insert(shapeArrayParameters, getShapeArray("switch","switch2_1_1", {1, 1, 4, 3}, { {"slide","bar5_1_1"},{"slide","bar6_1_1"} }))

    table.insert(shapeArrayParameters, getShapeArray("switch","switch1_2_2", {2, 2, 4, 3}, { {"slide","bar7_2_2"},{"slide","autoFan1_2_2"} }))
    table.insert(shapeArrayParameters, getShapeArray("switch","switch2_2_2", {2, 2, 6, 5}, { 
        {"slide","spitter1_1_4"},{"slide","spitter2_1_4"},{"slide","spitter3_1_4"},{"slide","spitter4_1_4"},
        {"slide","spitter6_1_4"},{"slide","spitter9_1_4"},{"slide","spitter10_1_4"},{"slide","spitter11_1_4"},
        {"door-open","door1_1_4"},{"door-open","door2_1_4"},
    }, {"one-way", "not-labelled"}))
    table.insert(shapeArrayParameters, getShapeArray("switch","switch1_1_3", {1, 3, 1, 4}, { {"door-open","door7_1_3"},{"slide","triangle3_1_3"},{"slide","bar1_1_3"} }))


    --GEMS
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 1, 2, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 1, 3, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 1, 2, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 1, 4, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 1, 5, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 1, 6, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 1, 7, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 2, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 2, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 2, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 4, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 6, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 1, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 7, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 7, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 7, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 4, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 2, 4, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 2, 2, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 2, 2, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 2, 1, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 2, 3, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 2, 3, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 2, 4, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 2, 5, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 2, 6, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 5, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 7, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 2, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 2, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 6, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 2, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 1, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 3, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 5, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 7, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 7, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 3, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 3, 4, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 4, 5, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 4, 5, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 4, 4, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {1, 4, 4, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 3, 1, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 3, 5, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 3, 5, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 3, 1, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 3, 3, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 3, 3, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 3, 6, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 3, 6, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 3, 4, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 3, 4, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 6, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 6, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 6, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 5, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 5, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 7, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 7, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 1, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 3, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 5, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 2, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 1, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 3, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 4, 1, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 5, 1, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 5, 3, 1}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 5, 3, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 5, 4, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 5, 2, 3}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 5, 2, 5}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 5, 6, 2}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purple", {2, 5, 6, 4}, "purple"))
    table.insert(shapeArrayParameters, getShapeArray("gem","redCoin", {1, 4, 4, 5}, "redCoin"))
    table.insert(shapeArrayParameters, getShapeArray("gem","blueCoin", {1, 1, 3, 1}, "blueCoin"))
    table.insert(shapeArrayParameters, getShapeArray("gem","purpleCoin", {2, 5, 2, 2}, "purpleCoin"))

    --ITEMS
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {1, 3, 2, 2}, 80))
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {1, 3, 7, 2}, 105))
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {1, 4, 5, 1}, 65))
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {1, 2, 1, 3}, 75))
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {1, 1, 7, 3}, 28))
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {1, 1, 2, 3}, 34))
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {2, 2, 1, 4}, 135))
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {2, 4, 4, 4}, 12))
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {2, 4, 3, 5}, 65))
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {2, 5, 6, 1}, 625))
    table.insert(shapeArrayParameters, getShapeArray("item","coins", {2, 5, 5, 5}, 74))
    table.insert(shapeArrayParameters, getShapeArray("item","small-present", {1, 4, 4, 2}, {}))

    table.insert(shapeArrayParameters, getShapeArray("item","small-present", {1, 3, 2, 5}, {}))

    table.insert(shapeArrayParameters, getShapeArray("item","small-present", {2, 2, 5, 1}, {}))

    table.insert(shapeArrayParameters, getShapeArray("item","small-present", {2, 5, 6, 3}, {}))

    table.insert(shapeArrayParameters, getShapeArray("item","small-present", {1, 4, 1, 4}, {}))

    table.insert(shapeArrayParameters, getShapeArray("item","big-present", {2, 3, 2, 2}, {}))

    table.insert(shapeArrayParameters, getShapeArray("item","big-present", {1, 1, 5, 5}, {}))

    table.insert(shapeArrayParameters, getShapeArray("item","big-present", {2, 5, 1, 4}, {}))


end
    t.createLevelObjects = createLevelObjects

t.thisScreenHorzValue = 1
t.thisScreenVertValue = 1
t.screenHorzTotal = 2
t.screenVertTotal = 5
t.ballFirstScreenHorzValue = 1
t.ballFirstScreenVertValue = 4
t.ballFirstHorzSquare = 1
t.ballFirstVertSquare = 3
t.ballFirstDirection = "right"
t.initialDirection = t.ballFirstDirection

return t
